### ISSUE TITLE
runme.dev seo

### ISSUE THREAD

**Issue by admc** [stateful/runme.dev#50]
Let's get runme.dev upgraded for SEO, inputs found here: https://app.ahrefs.com/site-audit/4344401/5/overview

- [ ] Sitemap, robots
- [ ] Meta tags
- [ ] H1's
- [ ] Canonical tags
- [ ] Open graph tags
- [ ] Alts on images
- [ ] Big files?

**Comment by admc** [comment]
@christian-bromann for stateful.com I'm using https://www.npmjs.com/package/next-sitemap to generate both the sitemap and the robots (which are important for the google search foo) - might be worth checking that out

**Comment by christian-bromann** [comment]
@admc Overall our SEO posture is pretty good already. I raised a PR with minor improvements that gets us a SEO Lighthouse score of 100. Let me know if I can do more.

> Sitemap, robots

A sitemap is already published at https://runme.dev/sitemap.xml, I can add a `robots.txt` however it is already defined as meta tag so that this would not be needed.

> Meta tags

The following meta tags are set: https://gist.github.com/christian-bromann/a22f7a9bf1d82184ddac63c93b20d44f .. please let me know which are missing.

> H1's

Can you describe what is missing here? Every main heading of sub pages in an `<h1 />` , excluding the typewrite one which is difficult given that a crawler would only see `Run your` anyway as the rest is added by JS.

> Canonical tags

I honestly don't see the need for adding one. Let me know which urls you want to change.

> Open graph tags

We have the following defined:

```html
<meta data-rh="true" property="og:site_name" content="Runme.dev" />
<meta data-rh="true" property="og:url" content="https://runme.dev" />
<meta data-rh="true" property="og:type" content="website" />
<meta data-rh="true" property="og:image" content="https://runme.dev/img/sidebyside.png" />
<meta data-rh="true" property="og:image" content="https://runme.dev/img/intro.gif" />
<meta data-rh="true" property="og:title" content="Runme: Run your Readme.md | Runme" />
```

Let me know if you like to modify them or add more.

> * Alts on images

I added some missing alt props. Let me know if more are missing.
